### ISSUE TITLE
Can't add theme again after update 

### ISSUE THREAD

**Issue by dviree** [sourcelocation/TrollTools#19] opened 2022-11-06 07:17 UTC
Getting this error when I try to re-import the theme 
![CA8B349C-3D78-4288-A9E4-226D8C6B4D59](https://user-images.githubusercontent.com/33899343/200158933-111a52b5-867d-4d43-9080-bbb6811bd8b2.png)

**Comment by sourcelocation** [comment] 2022-11-06 09:58
Duplicate of #14

**Closed as not planned by sourcelocation** 2022-11-06 09:58 UTC
Labels: duplicate
